#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libnfsidmap
Version  : 0.25
Release  : 5
URL      : http://www.citi.umich.edu/projects/nfsv4/linux/libnfsidmap/libnfsidmap-0.25.tar.gz
Source0  : http://www.citi.umich.edu/projects/nfsv4/linux/libnfsidmap/libnfsidmap-0.25.tar.gz
Summary  : Library that handles mapping between names and ids for NFSv4.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: libnfsidmap-lib
Requires: libnfsidmap-doc

%description
Library to help mapping id's, mainly for NFSv4.
When NFSv4 is using AUTH_GSS (which currently only supports Kerberos v5), the
NFSv4 server mapping functions MUST use secure communications.

%package dev
Summary: dev components for the libnfsidmap package.
Group: Development
Requires: libnfsidmap-lib

%description dev
dev components for the libnfsidmap package.


%package doc
Summary: doc components for the libnfsidmap package.
Group: Documentation

%description doc
doc components for the libnfsidmap package.


%package lib
Summary: lib components for the libnfsidmap package.
Group: Libraries

%description lib
lib components for the libnfsidmap package.


%prep
%setup -q -n libnfsidmap-0.25

%build
%configure --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/*.h
/usr/lib64/*.so
/usr/lib64/pkgconfig/*.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
%doc /usr/share/man/man5/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/*.so.*
/usr/lib64/libnfsidmap/nsswitch.so
/usr/lib64/libnfsidmap/static.so
